timezone: "Europe/Madrid"

universe:
  watchlist_csv: "data/watchlist.csv"

files:
  positions_csv: "data/positions.csv"
  signals_log_csv: "data/signals_log.csv"

data_source:
  provider: "yfinance"
  history:
    period: "220d"
    interval: "1d"

rules:
  entry:
    drop_lookback_days: 10 #10
    min_drop_pct: 10 #15
    rsi_period: 14 #14
    rsi_max_to_buy: 60.0 #30
    sma_window: 20 #50
    zscore_max_to_buy: -2 #-2

  exit:
    take_profit_pct: 15.0
    rsi_period: 14
    rsi_min_to_sell: 55.0
    sma_window: 50

  risk_guards:
    hard_stop_pct: -12.0
    time_stop_days: 60

logging:
  print_to_console: true


sizing:
  # Your portfolio snapshot (can change anytime)
  portfolio_value: 2000          # € total portfolio value
  available_cash_pct: 0.30        # % of portfolio currently in cash (e.g., 30%)

  # Risk framework (we’ll size from risk at stop)
  base_risk_per_trade_pct: 0.0075 # 0.75% of portfolio at risk per trade (before confidence)
  max_cash_per_trade_pct: 0.08    # hard cap: 8% of portfolio into one trade
  stop_pct: -12.0                 # assumed stop distance used for sizing
  max_open_trades: 8              # don’t suggest sizing if you exceed this

confidence:
  # Weights for the confidence score C in [0,1]
  weights:
    drop: 0.35
    rsi: 0.25
    zscore: 0.25
    volume: 0.15

  # Normalizations/caps for components
  regime_penalty_below_200dma: 0.8
  rsi_floor: 10           # RSI <= 10 treated as max oversold for scoring
  drop_hard_max: -25      # drop <= -25% treated as max for scoring
  zscore_hard_min: -4     # z <= -4σ treated as max for scoring
  volume_cap: 2.0         # volume spike capped at 2x average